<?php
/******************************************************
 * @package Ves Megamenu module for Magento 1.4.x.x and Magento 1.7.x.x
 * @version 1.0.0.1
 * @author http://landofcoder.com
 * @copyright	Copyright (C) December 2010 LandOfCoder.com <@emai:landofcoder@gmail.com>.All rights reserved.
 * @license		GNU General Public License version 2
*******************************************************/
$enable_offcanvas = Mage::getStoreConfig("ves_megamenu/ves_megamenu/enable_offcanvas");
$enable_vertical_offcanvas = Mage::getStoreConfig("ves_verticalmenu/ves_verticalmenu/enable_offcanvas");
if(!$enable_vertical_offcanvas) {
	$enable_offcanvas = true;
}
?>
<div class="ves-megamenu  <?php if(!$enable_offcanvas): ?>hidden-xs hidden-sm<?php else: ?> offcanvas-actived<?php endif; ?>">
	<div class="navbar navbar-inverse">
		<div id="mainmenutop" class="megamenu offset-canvas-menu-play" role="navigation"  data-offcanvas="<?php echo $enable_offcanvas?'true':'false'; ?>">
			<div class="navbar">
				<a href="javascript:;" data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			     </a>
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<div class="close-mobile-nav close-block hidden-lg hidden-md">
						<?php echo $this->getChildHtml("top.menu.top"); ?>
					</div>
					<?php echo $menuHtml; ?>
					<div class="menu-footer hidden-lg hidden-md">
						<?php echo $this->getChildHtml("top.menu.footer"); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
jQuery(window).ready( function(){

	/*  Fix First Click Menu */
	jQuery(document.body).on('click', '#mainmenutop [data-toggle="dropdown"]' ,function(event){
		event.stopImmediatePropagation();
		jQuery(this).parent().show();
		if(!jQuery(this).parent().hasClass('open') && this.href && this.href != '#'){
			window.location.href = this.href;
		}

	});
	jQuery(document.body).on('dblclick', '#mainmenutop [data-toggle="dropdown"]' ,function(event){
		event.stopImmediatePropagation();
		jQuery(this).parent().show();
		if(!jQuery(this).parent().hasClass('open') && this.href && this.href != '#'){
			window.location.href = this.href;
		}

	});
});
</script>