<?php 
  $widget = $this->getWidget(); 
  $show_name = isset($widget['show_name'])?$widget['show_name']: 1;
  $brands = isset($widget['brands'])?$widget['brands']: array();
  $image_height = isset($widget['image_height'])?$widget['image_height']: 200;
  $image_width = isset($widget['image_width'])?$widget['image_width']: 200;
  if($brands) {
?>
<?php if( isset($widget['widget_name']) & $show_name){
?>
<div class="menu-title"><?php echo $widget['widget_name'];?></div>
<?php
}?>
<div class="widget-brand-list">
  <div class="widget-inner">
      <ul class="brands-list">
      <?php foreach ($brands as $brand) { ?>
      <li class="post-item itemcol">
        <h3><a href="<?php echo $brand->getLink();?>" title="<?php echo $brand->getTitle();?>"><?php echo $brand->getTitle(); ?></a></h3>
        <div class="post-image">
          <a href="<?php echo $brand->getLink();?>" title="<?php echo $brand->getTitle();?>">
          <?php
               $image = "";
               if($image_height && $image_width) {
                $image = Mage::helper('ves_verticalmenu')->resizeImage($brand->getFile(), $image_width, $image_height);
               } else {
                $image = $brand->getImageUrl("l");
               }
              ?>
          <img src="<?php echo $image; ?>" class="post-image img-responsive" alt="<?php echo $brand->getTitle();?>"/>
        </a>
        </div>
      </li>
      <?php } ?>
      </ul>
      
  </div>
</div>
<?php } ?>