<?php
/******************************************************
 * @package Ves Megamenu module for Magento 1.4.x.x and Magento 1.7.x.x
 * @version 1.0.0.1
 * @author http://landofcoder.com
 * @copyright	Copyright (C) December 2010 LandOfCoder.com <@emai:landofcoder@gmail.com>.All rights reserved.
 * @license		GNU General Public License version 2
*******************************************************/
$title = $this->getConfig("title");
$enable_offcanvas = Mage::getStoreConfig("ves_verticalmenu/ves_verticalmenu/enable_offcanvas");
?>
<div id="ves-verticalmenu" class="block ves-verticalmenu highlighted <?php if(!$enable_offcanvas): ?>hidden-xs hidden-sm<?php else: ?> offcanvas-actived<?php endif; ?>">
	<?php if($title) { ?>
	<div class="block-title <?php if($enable_offcanvas): ?>hidden-xs hidden-sm<?php endif; ?>">
		<span><?php echo $title; ?></span>	
		<span class="shapes round">
			<em class="shapes bottom"></em>
		</span>
	</div>
	<?php } ?>
	<div class="block-content">
		<div class="navbar navbar-inverse">
			<div id="verticalmenu" class="verticalmenu offset-canvas-menu-play" role="navigation" data-offcanvas="<?php echo $enable_offcanvas?'true':'false'; ?>">
				<div class="navbar">
					<a href="javascript:;" data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle">
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				     </a>
					<div class="collapse navbar-collapse navbar-ex1-collapse">
						<div class="close-mobile-nav close-block hidden-lg hidden-md">
							<?php echo $this->getChildHtml("verticalmenu.menu.top"); ?>
						</div>
						<?php echo $menuHtml; ?>
						<div class="menu-footer hidden-lg hidden-md">
							<?php echo $this->getChildHtml("verticalmenu.menu.footer"); ?>
						</div>
					 </div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
jQuery(window).ready( function(){

	/*  Fix First Click Menu */
	jQuery(document.body).on('click', '#verticalmenu [data-toggle="dropdown"]' ,function(event){
		event.stopImmediatePropagation();
		jQuery(this).parent().show();
		if(!jQuery(this).parent().hasClass('open') && this.href && this.href != '#'){
			window.location.href = this.href;
		}

	});
	jQuery(document.body).on('dblclick', '#verticalmenu [data-toggle="dropdown"]' ,function(event){
		event.stopImmediatePropagation();
		jQuery(this).parent().show();
		if(!jQuery(this).parent().hasClass('open') && this.href && this.href != '#'){
			window.location.href = this.href;
		}

	});
});
</script>